Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
wrapper = fso.BuildPath(scriptDir, "ahr_wrapper.ps1")
cmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File " & Chr(34) & wrapper & Chr(34)
WScript.Quit shell.Run(cmd, 0, True)
